import { normalizeLanguage, tOption } from './i18n.js';

export const presets = {
  combat: {action:'attack', situation:'standing', path:'stationary', frames:16, grid:'4x4', loop:true},
  idle: {action:'idle', situation:'standing', path:'stationary', frames:16, grid:'4x4', loop:true},
  standing: {action:'breathe', situation:'standing', path:'stationary', frames:16, grid:'4x4', loop:true},
  sitting: {action:'breathe', situation:'sittingChair', path:'stationary', frames:16, grid:'4x4', loop:true},
  lying: {action:'breathe', situation:'lyingSide', path:'stationary', frames:16, grid:'4x4', loop:true},
  sleep: {action:'sleep', situation:'sleeping', path:'stationary', frames:16, grid:'4x4', loop:true},
  wake: {action:'wake', situation:'sleeping', path:'stationary', frames:16, grid:'4x4', loop:false},
  sitDown: {action:'sitDown', situation:'standing', path:'stationary', frames:12, grid:'3x4', loop:false},
  standUp: {action:'standUp', situation:'sittingChair', path:'stationary', frames:12, grid:'3x4', loop:false},
  lieDown: {action:'lieDown', situation:'standing', path:'stationary', frames:12, grid:'3x4', loop:false},
  getUp: {action:'getUp', situation:'lyingBack', path:'stationary', frames:12, grid:'3x4', loop:false},
  walk: {action:'walk', situation:'standing', path:'forward', frames:16, grid:'4x4', loop:true},
  jog: {action:'jog', situation:'standing', path:'forward', frames:16, grid:'4x4', loop:true},
  run: {action:'run', situation:'standing', path:'forward', frames:16, grid:'4x4', loop:true},
  tiptoe: {action:'tiptoe', situation:'standing', path:'forward', frames:16, grid:'4x4', loop:true},
  crawl: {action:'crawl', situation:'allFours', path:'forward', frames:12, grid:'3x4', loop:true},
  jump: {action:'jump', situation:'standing', path:'up', frames:16, grid:'4x4', loop:false},
  fall: {action:'fall', situation:'airborne', path:'down', frames:12, grid:'3x4', loop:false},
  landing: {action:'land', situation:'airborne', path:'down', frames:12, grid:'3x4', loop:false},
  slide: {action:'slide', situation:'crouching', path:'forward', frames:12, grid:'3x4', loop:false},
  roll: {action:'roll', situation:'crouching', path:'forward', frames:12, grid:'3x4', loop:false},
  dodge: {action:'dodge', situation:'standing', path:'leftRight', frames:12, grid:'3x4', loop:false},
  fly: {action:'fly', situation:'flying', path:'forward', frames:16, grid:'4x4', loop:true},
  hover: {action:'hover', situation:'hovering', path:'stationary', frames:16, grid:'4x4', loop:true},
  glide: {action:'glide', situation:'flying', path:'arc', frames:16, grid:'4x4', loop:true},
  zeroGravity: {action:'floatWater', situation:'zeroGravity', path:'circle', frames:16, grid:'4x4', loop:true},
  swim: {action:'swim', situation:'swimming', path:'forward', frames:16, grid:'4x4', loop:true},
  treadWater: {action:'treadWater', situation:'floatingWater', path:'stationary', frames:16, grid:'4x4', loop:true},
  climb: {action:'climb', situation:'climbing', path:'up', frames:16, grid:'4x4', loop:true},
  dance: {action:'dance', situation:'standing', path:'stationary', frames:16, grid:'4x4', loop:true},
  emote: {action:'gesture', situation:'standing', path:'stationary', frames:16, grid:'4x4', loop:true},
  interaction: {action:'pickUp', situation:'standing', path:'stationary', frames:12, grid:'3x4', loop:false},
  rotation: {action:'rotate', situation:'neutral', path:'stationary', frames:8, grid:'4x2', loop:true},
  storyboard: {action:'custom', situation:'neutral', path:'stationary', frames:8, grid:'4x2', loop:false},
  custom: {action:'custom', situation:'neutral', path:'stationary', frames:16, grid:'4x4', loop:true}
};

const PHASES = {
'ko-KR':{neutral:'중립 자세',settle:'안정',inhale:'들이마심',rise:'상체가 미세하게 올라감',secondary:'머리·옷·꼬리 등 2차 움직임',blink:'눈깜박임',exhale:'내쉬기',loop:'첫 프레임과 연결',enterPose:'목표 자세로 들어감',holdPose:'자세 유지',micro:'미세한 균형 변화',contactA:'첫 접지',downA:'하강·압축',passA:'패싱',upA:'상승',contactB:'반대쪽 접지',downB:'반대쪽 하강',passB:'반대쪽 패싱',upB:'반대쪽 상승',compress:'최대 압축',pushOff:'추진',flight:'비행 구간',handPlant:'손 접지',kneeDrive:'무릎 전진',bodyShift:'몸통 중심 이동',advance:'앞으로 전진',reach:'손/발을 뻗음',grip:'접촉·그립',pull:'당겨 올라감',step:'다음 지점에 발을 둠',crouch:'몸을 낮춰 준비',takeoff:'이륙',ascent:'상승',apex:'정점',descent:'하강',preLand:'착지 직전',impact:'충격 피크',recover:'회복',airborne:'공중 상태',gravity:'중력에 의해 하강 시작',fallFast:'하강 가속',touchDown:'첫 접지',absorb:'충격 흡수',threat:'위험 인지',shift:'무게중심 이동',initiate:'동작 시작',accelerate:'가속',peak:'동작 피크',rebound:'반동',tuck:'몸을 말아 넣음',rollStart:'구르기 시작',inverted:'회전 중간',rollExit:'구르기 종료',takeFlight:'비행 시작',bank:'기울여 방향 전환',cruise:'안정 비행',turn:'방향 전환',hoverUp:'미세 상승',hoverDown:'미세 하강',correct:'자세 보정',strokeA:'첫 스트로크',catchA:'물 잡기',pullA:'당기기',kickA:'킥/추진',glide:'활주',strokeB:'반대 스트로크',catchB:'반대쪽 물 잡기',pullB:'반대쪽 당기기',kickB:'반대쪽 킥',ready:'준비 자세',anticipation:'예비동작',windup:'예비동작 최대',preImpact:'임팩트 직전',follow:'후속 동작',recoil:'반동 정리',rhythm:'리듬 진입',accent:'주 동작 강조',finish:'마무리 포즈',expression:'표정 변화 시작',gesture:'손·상체 제스처',emotionPeak:'감정 피크',release:'완화 시작',approach:'대상에 접근',objectContact:'오브젝트 접촉',manipulate:'잡기·밀기·사용 등 조작',return:'원래 자세로 복귀',eyesClosed:'눈을 감은 상태',sleepBreath:'수면 호흡',stir:'몸을 미세하게 움직임',eyesOpen:'눈을 뜸',headLift:'머리·상체를 듦',sitUp:'몸을 일으킴',orient:'주변을 확인',start:'시작 자세',prep:'준비',develop:'동작 전개',prePeak:'피크 직전',decelerate:'감속',end:'끝 자세'},
'en-US':{neutral:'neutral pose',settle:'settle',inhale:'inhale',rise:'slight torso rise',secondary:'secondary hair/clothing/tail motion',blink:'blink',exhale:'exhale',loop:'connect to frame 1',enterPose:'enter target pose',holdPose:'hold pose',micro:'subtle balance shift',contactA:'first contact',downA:'down / compression',passA:'passing position',upA:'up position',contactB:'opposite contact',downB:'opposite down',passB:'opposite passing',upB:'opposite up',compress:'maximum compression',pushOff:'push-off',flight:'flight phase',handPlant:'hand plant',kneeDrive:'knee drive',bodyShift:'torso weight shift',advance:'advance forward',reach:'reach with hand / foot',grip:'contact and grip',pull:'pull body upward',step:'place foot on next hold',crouch:'crouch to prepare',takeoff:'takeoff',ascent:'ascent',apex:'apex',descent:'descent',preLand:'pre-landing',impact:'impact peak',recover:'recovery',airborne:'airborne state',gravity:'gravity takes over',fallFast:'accelerating descent',touchDown:'first touchdown',absorb:'absorb impact',threat:'read the threat',shift:'weight shift',initiate:'action begins',accelerate:'acceleration',peak:'action peak',rebound:'rebound',tuck:'tuck body',rollStart:'roll begins',inverted:'mid-roll inversion',rollExit:'exit roll',takeFlight:'enter flight',bank:'bank / change heading',cruise:'stable cruise',turn:'turn',hoverUp:'slight rise',hoverDown:'slight drop',correct:'posture correction',strokeA:'first stroke',catchA:'water catch',pullA:'pull phase',kickA:'kick / propulsion',glide:'glide',strokeB:'opposite stroke',catchB:'opposite catch',pullB:'opposite pull',kickB:'opposite kick',ready:'ready stance',anticipation:'anticipation',windup:'maximum wind-up',preImpact:'pre-impact',follow:'follow-through',recoil:'recoil / settle',rhythm:'enter rhythm',accent:'main accent',finish:'finish pose',expression:'expression begins',gesture:'hand / torso gesture',emotionPeak:'emotion peak',release:'release begins',approach:'approach target',objectContact:'contact object',manipulate:'grasp / push / use / manipulate',return:'return to base pose',eyesClosed:'eyes closed',sleepBreath:'sleep breathing',stir:'small stir',eyesOpen:'eyes open',headLift:'lift head / torso',sitUp:'sit up',orient:'orient and look around',start:'start pose',prep:'preparation',develop:'action develops',prePeak:'pre-peak',decelerate:'deceleration',end:'end pose'},
'ja-JP':{neutral:'ニュートラルポーズ',settle:'安定',inhale:'吸う',rise:'上体がわずかに上がる',secondary:'髪・服・尾などの二次動作',blink:'まばたき',exhale:'吐く',loop:'1フレーム目につなぐ',enterPose:'目標ポーズに入る',holdPose:'ポーズ維持',micro:'微細な重心移動',contactA:'最初の接地',downA:'下降・圧縮',passA:'パッシング',upA:'上昇',contactB:'反対側の接地',downB:'反対側の下降',passB:'反対側のパッシング',upB:'反対側の上昇',compress:'最大圧縮',pushOff:'蹴り出し',flight:'滞空',handPlant:'手を接地',kneeDrive:'膝を前へ',bodyShift:'胴体の重心移動',advance:'前進',reach:'手 / 足を伸ばす',grip:'接触してつかむ',pull:'体を引き上げる',step:'次の足場へ足を置く',crouch:'低く構える',takeoff:'離陸',ascent:'上昇',apex:'頂点',descent:'下降',preLand:'着地直前',impact:'衝撃ピーク',recover:'回復',airborne:'空中状態',gravity:'重力で下降開始',fallFast:'下降加速',touchDown:'最初の接地',absorb:'衝撃吸収',threat:'危険を認識',shift:'重心移動',initiate:'動作開始',accelerate:'加速',peak:'動作ピーク',rebound:'反動',tuck:'体を丸める',rollStart:'回転開始',inverted:'回転中盤',rollExit:'回転終了',takeFlight:'飛行開始',bank:'バンクして方向変更',cruise:'安定飛行',turn:'旋回',hoverUp:'わずかに上昇',hoverDown:'わずかに下降',correct:'姿勢補正',strokeA:'最初のストローク',catchA:'水を捉える',pullA:'プル',kickA:'キック / 推進',glide:'グライド',strokeB:'反対側ストローク',catchB:'反対側キャッチ',pullB:'反対側プル',kickB:'反対側キック',ready:'準備姿勢',anticipation:'予備動作',windup:'予備動作最大',preImpact:'インパクト直前',follow:'フォロースルー',recoil:'反動を整える',rhythm:'リズムに入る',accent:'主動作のアクセント',finish:'決めポーズ',expression:'表情変化開始',gesture:'手・上体のジェスチャー',emotionPeak:'感情ピーク',release:'緩和開始',approach:'対象へ近づく',objectContact:'物体に接触',manipulate:'つかむ・押す・操作する',return:'基本姿勢へ戻る',eyesClosed:'目を閉じた状態',sleepBreath:'睡眠時の呼吸',stir:'小さく身じろぎ',eyesOpen:'目を開く',headLift:'頭・上体を起こす',sitUp:'起き上がる',orient:'周囲を確認',start:'開始ポーズ',prep:'準備',develop:'動作展開',prePeak:'ピーク直前',decelerate:'減速',end:'終了ポーズ'},
'zh-CN':{neutral:'中性姿势',settle:'稳定',inhale:'吸气',rise:'上身轻微抬起',secondary:'头发/衣物/尾巴的次级运动',blink:'眨眼',exhale:'呼气',loop:'连接回第1帧',enterPose:'进入目标姿势',holdPose:'保持姿势',micro:'轻微重心变化',contactA:'第一次接地',downA:'下沉 / 压缩',passA:'经过位',upA:'上升位',contactB:'另一侧接地',downB:'另一侧下沉',passB:'另一侧经过位',upB:'另一侧上升',compress:'最大压缩',pushOff:'蹬地推进',flight:'腾空阶段',handPlant:'手部撑地',kneeDrive:'膝部前驱',bodyShift:'躯干重心移动',advance:'向前推进',reach:'伸出手 / 脚',grip:'接触并抓握',pull:'拉动身体向上',step:'脚踩下一个支点',crouch:'下蹲准备',takeoff:'离地',ascent:'上升',apex:'最高点',descent:'下降',preLand:'落地前',impact:'冲击峰值',recover:'恢复',airborne:'空中状态',gravity:'重力接管',fallFast:'加速下降',touchDown:'首次触地',absorb:'吸收冲击',threat:'感知威胁',shift:'重心移动',initiate:'动作开始',accelerate:'加速',peak:'动作峰值',rebound:'反弹',tuck:'收紧身体',rollStart:'开始翻滚',inverted:'翻滚中段',rollExit:'退出翻滚',takeFlight:'进入飞行',bank:'倾斜转向',cruise:'稳定巡航',turn:'转向',hoverUp:'轻微上升',hoverDown:'轻微下降',correct:'姿态修正',strokeA:'第一次划水',catchA:'抓水',pullA:'拉水',kickA:'打腿 / 推进',glide:'滑行',strokeB:'另一侧划水',catchB:'另一侧抓水',pullB:'另一侧拉水',kickB:'另一侧打腿',ready:'准备姿势',anticipation:'预备动作',windup:'预备动作最大',preImpact:'冲击前',follow:'跟随动作',recoil:'反冲 / 稳定',rhythm:'进入节奏',accent:'主动作强调',finish:'结束姿势',expression:'表情开始变化',gesture:'手部 / 上身手势',emotionPeak:'情绪峰值',release:'开始放松',approach:'接近目标',objectContact:'接触物体',manipulate:'抓取 / 推动 / 使用 / 操作',return:'回到基础姿势',eyesClosed:'闭眼状态',sleepBreath:'睡眠呼吸',stir:'轻微翻动',eyesOpen:'睁眼',headLift:'抬头 / 抬起上身',sitUp:'坐起',orient:'观察周围',start:'起始姿势',prep:'准备',develop:'动作展开',prePeak:'峰值前',decelerate:'减速',end:'结束姿势'},
'es-ES':{neutral:'pose neutra',settle:'estabilizar',inhale:'inhalar',rise:'ligera elevación del torso',secondary:'movimiento secundario de pelo/ropa/cola',blink:'parpadeo',exhale:'exhalar',loop:'conectar con el fotograma 1',enterPose:'entrar en la pose objetivo',holdPose:'mantener la pose',micro:'cambio sutil de equilibrio',contactA:'primer contacto',downA:'bajada / compresión',passA:'posición de paso',upA:'posición elevada',contactB:'contacto opuesto',downB:'bajada opuesta',passB:'paso opuesto',upB:'elevación opuesta',compress:'compresión máxima',pushOff:'impulso',flight:'fase de vuelo',handPlant:'apoyo de mano',kneeDrive:'avance de rodilla',bodyShift:'cambio de peso del torso',advance:'avance',reach:'extender mano / pie',grip:'contacto y agarre',pull:'tirar del cuerpo hacia arriba',step:'poner el pie en el siguiente apoyo',crouch:'agacharse para preparar',takeoff:'despegue',ascent:'ascenso',apex:'punto máximo',descent:'descenso',preLand:'antes de aterrizar',impact:'pico de impacto',recover:'recuperación',airborne:'estado en el aire',gravity:'la gravedad toma control',fallFast:'descenso acelerado',touchDown:'primer contacto con el suelo',absorb:'absorber impacto',threat:'detectar amenaza',shift:'cambio de peso',initiate:'inicio de acción',accelerate:'aceleración',peak:'pico de acción',rebound:'rebote',tuck:'encoger el cuerpo',rollStart:'inicio del giro',inverted:'mitad del giro',rollExit:'salida del giro',takeFlight:'entrar en vuelo',bank:'inclinar para cambiar rumbo',cruise:'vuelo estable',turn:'giro',hoverUp:'ligero ascenso',hoverDown:'ligero descenso',correct:'corrección de postura',strokeA:'primera brazada',catchA:'agarre del agua',pullA:'fase de tirón',kickA:'patada / propulsión',glide:'deslizamiento',strokeB:'brazada opuesta',catchB:'agarre opuesto',pullB:'tirón opuesto',kickB:'patada opuesta',ready:'postura preparada',anticipation:'anticipación',windup:'preparación máxima',preImpact:'antes del impacto',follow:'seguimiento',recoil:'retroceso / estabilización',rhythm:'entrar en ritmo',accent:'acento principal',finish:'pose final',expression:'empieza la expresión',gesture:'gesto de manos / torso',emotionPeak:'pico emocional',release:'empieza a soltar',approach:'acercarse al objetivo',objectContact:'contactar el objeto',manipulate:'agarrar / empujar / usar / manipular',return:'volver a la pose base',eyesClosed:'ojos cerrados',sleepBreath:'respiración al dormir',stir:'pequeño movimiento',eyesOpen:'abrir los ojos',headLift:'levantar cabeza / torso',sitUp:'incorporarse',orient:'orientarse y mirar alrededor',start:'pose inicial',prep:'preparación',develop:'desarrollo de la acción',prePeak:'antes del pico',decelerate:'desaceleración',end:'pose final'},
'fr-FR':{neutral:'pose neutre',settle:'stabilisation',inhale:'inspiration',rise:'légère montée du torse',secondary:'mouvement secondaire cheveux/vêtements/queue',blink:'clignement des yeux',exhale:'expiration',loop:'raccorder à l’image 1',enterPose:'entrer dans la pose cible',holdPose:'tenir la pose',micro:'léger transfert d’équilibre',contactA:'premier contact',downA:'descente / compression',passA:'position de passage',upA:'position haute',contactB:'contact opposé',downB:'descente opposée',passB:'passage opposé',upB:'montée opposée',compress:'compression maximale',pushOff:'impulsion',flight:'phase aérienne',handPlant:'appui de la main',kneeDrive:'avancée du genou',bodyShift:'transfert du torse',advance:'avancer',reach:'tendre main / pied',grip:'contact et prise',pull:'tirer le corps vers le haut',step:'placer le pied sur l’appui suivant',crouch:'s’accroupir pour préparer',takeoff:'décollage',ascent:'montée',apex:'sommet',descent:'descente',preLand:'avant l’atterrissage',impact:'pic d’impact',recover:'récupération',airborne:'état aérien',gravity:'la gravité prend le relais',fallFast:'descente accélérée',touchDown:'premier contact au sol',absorb:'absorber l’impact',threat:'détecter la menace',shift:'transfert de poids',initiate:'début de l’action',accelerate:'accélération',peak:'pic de l’action',rebound:'rebond',tuck:'ramener le corps',rollStart:'début de la roulade',inverted:'milieu de roulade',rollExit:'sortie de roulade',takeFlight:'passage en vol',bank:'inclinaison / changement de cap',cruise:'vol stable',turn:'virage',hoverUp:'légère montée',hoverDown:'légère descente',correct:'correction de posture',strokeA:'premier mouvement de nage',catchA:'prise d’eau',pullA:'traction',kickA:'battement / propulsion',glide:'glisse',strokeB:'mouvement opposé',catchB:'prise opposée',pullB:'traction opposée',kickB:'battement opposé',ready:'pose prête',anticipation:'anticipation',windup:'préparation maximale',preImpact:'avant impact',follow:'accompagnement',recoil:'recul / stabilisation',rhythm:'entrer dans le rythme',accent:'accent principal',finish:'pose finale',expression:'début de l’expression',gesture:'geste mains / torse',emotionPeak:'pic émotionnel',release:'début du relâchement',approach:'s’approcher de la cible',objectContact:'contact avec l’objet',manipulate:'saisir / pousser / utiliser / manipuler',return:'revenir à la pose de base',eyesClosed:'yeux fermés',sleepBreath:'respiration de sommeil',stir:'petit mouvement',eyesOpen:'ouvrir les yeux',headLift:'lever tête / torse',sitUp:'se redresser',orient:'s’orienter et regarder autour',start:'pose de départ',prep:'préparation',develop:'développement de l’action',prePeak:'avant le pic',decelerate:'décélération',end:'pose finale'},
'de-DE':{neutral:'neutrale Pose',settle:'stabilisieren',inhale:'einatmen',rise:'leichte Oberkörperhebung',secondary:'Sekundärbewegung von Haar/Kleidung/Schwanz',blink:'blinzeln',exhale:'ausatmen',loop:'zu Frame 1 zurückführen',enterPose:'Zielpose einnehmen',holdPose:'Pose halten',micro:'kleine Gewichtsverlagerung',contactA:'erster Kontakt',downA:'Absenken / Kompression',passA:'Passierposition',upA:'Hochposition',contactB:'Gegenkontakt',downB:'Gegenabsenkung',passB:'Gegen-Passierposition',upB:'Gegen-Hochposition',compress:'maximale Kompression',pushOff:'Abdruck',flight:'Flugphase',handPlant:'Hand aufsetzen',kneeDrive:'Knie vorführen',bodyShift:'Rumpfgewicht verlagern',advance:'vorwärts bewegen',reach:'Hand / Fuß ausstrecken',grip:'Kontakt und Griff',pull:'Körper hochziehen',step:'Fuß auf nächsten Halt setzen',crouch:'zur Vorbereitung absenken',takeoff:'Abheben',ascent:'Aufstieg',apex:'Scheitelpunkt',descent:'Abstieg',preLand:'vor der Landung',impact:'Aufprallspitze',recover:'Erholung',airborne:'in der Luft',gravity:'Schwerkraft übernimmt',fallFast:'beschleunigter Fall',touchDown:'erster Bodenkontakt',absorb:'Aufprall abfangen',threat:'Gefahr erkennen',shift:'Gewicht verlagern',initiate:'Aktion beginnt',accelerate:'Beschleunigung',peak:'Aktionshöhepunkt',rebound:'Rückfederung',tuck:'Körper einrollen',rollStart:'Rolle beginnt',inverted:'Mitte der Rolle',rollExit:'Rolle verlassen',takeFlight:'in den Flug übergehen',bank:'neigen / Kurs ändern',cruise:'stabiler Flug',turn:'drehen',hoverUp:'leicht steigen',hoverDown:'leicht sinken',correct:'Haltung korrigieren',strokeA:'erster Schwimmzug',catchA:'Wasser fassen',pullA:'Zugphase',kickA:'Beinschlag / Antrieb',glide:'gleiten',strokeB:'Gegenzug',catchB:'Gegenfassen',pullB:'Gegenzugphase',kickB:'Gegenbeinschlag',ready:'Bereitschaftspose',anticipation:'Ausholbewegung',windup:'maximale Vorbereitung',preImpact:'vor dem Treffer',follow:'Nachbewegung',recoil:'Rückstoß / Stabilisierung',rhythm:'in den Rhythmus kommen',accent:'Hauptakzent',finish:'Schlusspose',expression:'Mimik beginnt',gesture:'Hand-/Rumpfgeste',emotionPeak:'Emotionshöhepunkt',release:'Entspannung beginnt',approach:'Ziel annähern',objectContact:'Objektkontakt',manipulate:'greifen / schieben / nutzen / bedienen',return:'zur Grundpose zurückkehren',eyesClosed:'Augen geschlossen',sleepBreath:'Schlafatmung',stir:'kleine Bewegung',eyesOpen:'Augen öffnen',headLift:'Kopf / Oberkörper anheben',sitUp:'aufrichten',orient:'orientieren und umsehen',start:'Startpose',prep:'Vorbereitung',develop:'Aktion entwickelt sich',prePeak:'vor dem Höhepunkt',decelerate:'abbremsen',end:'Endpose'},
'pt-BR':{neutral:'pose neutra',settle:'estabilizar',inhale:'inspirar',rise:'leve elevação do tronco',secondary:'movimento secundário de cabelo/roupa/cauda',blink:'piscar',exhale:'expirar',loop:'conectar ao quadro 1',enterPose:'entrar na pose alvo',holdPose:'manter a pose',micro:'pequena mudança de equilíbrio',contactA:'primeiro contato',downA:'descida / compressão',passA:'posição de passagem',upA:'posição alta',contactB:'contato oposto',downB:'descida oposta',passB:'passagem oposta',upB:'subida oposta',compress:'compressão máxima',pushOff:'impulso',flight:'fase aérea',handPlant:'apoio da mão',kneeDrive:'avanço do joelho',bodyShift:'mudança de peso do tronco',advance:'avançar',reach:'estender mão / pé',grip:'contato e pegada',pull:'puxar o corpo para cima',step:'colocar o pé no próximo apoio',crouch:'agachar para preparar',takeoff:'decolagem',ascent:'subida',apex:'ápice',descent:'descida',preLand:'antes do pouso',impact:'pico de impacto',recover:'recuperação',airborne:'estado no ar',gravity:'gravidade assume',fallFast:'descida acelerada',touchDown:'primeiro contato com o chão',absorb:'absorver impacto',threat:'perceber ameaça',shift:'mudança de peso',initiate:'ação começa',accelerate:'aceleração',peak:'pico da ação',rebound:'rebote',tuck:'recolher o corpo',rollStart:'início do rolamento',inverted:'meio do rolamento',rollExit:'saída do rolamento',takeFlight:'entrar em voo',bank:'inclinar / mudar direção',cruise:'voo estável',turn:'virar',hoverUp:'leve subida',hoverDown:'leve descida',correct:'correção de postura',strokeA:'primeira braçada',catchA:'agarre da água',pullA:'fase de puxada',kickA:'pernada / propulsão',glide:'deslize',strokeB:'braçada oposta',catchB:'agarre oposto',pullB:'puxada oposta',kickB:'pernada oposta',ready:'pose pronta',anticipation:'antecipação',windup:'preparação máxima',preImpact:'antes do impacto',follow:'continuação',recoil:'recuo / estabilização',rhythm:'entrar no ritmo',accent:'acento principal',finish:'pose final',expression:'expressão começa',gesture:'gesto de mãos / tronco',emotionPeak:'pico emocional',release:'começa a relaxar',approach:'aproximar-se do alvo',objectContact:'contato com o objeto',manipulate:'agarrar / empurrar / usar / manipular',return:'voltar à pose base',eyesClosed:'olhos fechados',sleepBreath:'respiração de sono',stir:'pequeno movimento',eyesOpen:'abrir os olhos',headLift:'levantar cabeça / tronco',sitUp:'sentar-se',orient:'orientar-se e olhar ao redor',start:'pose inicial',prep:'preparação',develop:'ação se desenvolve',prePeak:'antes do pico',decelerate:'desaceleração',end:'pose final'},
'it-IT':{neutral:'posa neutra',settle:'stabilizzazione',inhale:'inspirare',rise:'leggero sollevamento del busto',secondary:'movimento secondario di capelli/vestiti/coda',blink:'battito di ciglia',exhale:'espirare',loop:'collegare al fotogramma 1',enterPose:'entrare nella posa obiettivo',holdPose:'mantenere la posa',micro:'piccolo cambio di equilibrio',contactA:'primo contatto',downA:'discesa / compressione',passA:'posizione di passaggio',upA:'posizione alta',contactB:'contatto opposto',downB:'discesa opposta',passB:'passaggio opposto',upB:'salita opposta',compress:'compressione massima',pushOff:'spinta',flight:'fase di volo',handPlant:'appoggio della mano',kneeDrive:'avanzamento del ginocchio',bodyShift:'spostamento del peso del busto',advance:'avanzare',reach:'estendere mano / piede',grip:'contatto e presa',pull:'tirare il corpo verso l’alto',step:'mettere il piede sul prossimo appoggio',crouch:'abbassarsi per preparare',takeoff:'decollo',ascent:'salita',apex:'apice',descent:'discesa',preLand:'prima dell’atterraggio',impact:'picco d’impatto',recover:'recupero',airborne:'stato in aria',gravity:'la gravità prende il controllo',fallFast:'discesa accelerata',touchDown:'primo contatto a terra',absorb:'assorbire l’impatto',threat:'percepire la minaccia',shift:'spostamento del peso',initiate:'inizio azione',accelerate:'accelerazione',peak:'picco dell’azione',rebound:'rimbalzo',tuck:'raccogliere il corpo',rollStart:'inizio rotolamento',inverted:'metà rotolamento',rollExit:'uscita dal rotolamento',takeFlight:'entrare in volo',bank:'inclinarsi / cambiare rotta',cruise:'volo stabile',turn:'virata',hoverUp:'leggera salita',hoverDown:'leggera discesa',correct:'correzione della posa',strokeA:'prima bracciata',catchA:'presa dell’acqua',pullA:'fase di trazione',kickA:'calcio / propulsione',glide:'scivolamento',strokeB:'bracciata opposta',catchB:'presa opposta',pullB:'trazione opposta',kickB:'calcio opposto',ready:'posa pronta',anticipation:'anticipazione',windup:'preparazione massima',preImpact:'prima dell’impatto',follow:'seguito del movimento',recoil:'rinculo / stabilizzazione',rhythm:'entrare nel ritmo',accent:'accento principale',finish:'posa finale',expression:'inizio espressione',gesture:'gesto di mani / busto',emotionPeak:'picco emotivo',release:'inizio rilascio',approach:'avvicinarsi al bersaglio',objectContact:'contatto con l’oggetto',manipulate:'afferrare / spingere / usare / manipolare',return:'tornare alla posa base',eyesClosed:'occhi chiusi',sleepBreath:'respiro nel sonno',stir:'piccolo movimento',eyesOpen:'aprire gli occhi',headLift:'sollevare testa / busto',sitUp:'mettersi seduto',orient:'orientarsi e guardare intorno',start:'posa iniziale',prep:'preparazione',develop:'sviluppo dell’azione',prePeak:'prima del picco',decelerate:'decelerazione',end:'posa finale'},
'ru-RU':{neutral:'нейтральная поза',settle:'стабилизация',inhale:'вдох',rise:'лёгкий подъём корпуса',secondary:'вторичное движение волос/одежды/хвоста',blink:'моргание',exhale:'выдох',loop:'соединить с кадром 1',enterPose:'войти в целевую позу',holdPose:'удерживать позу',micro:'небольшое смещение баланса',contactA:'первый контакт',downA:'опускание / сжатие',passA:'проходящая позиция',upA:'верхняя позиция',contactB:'противоположный контакт',downB:'противоположное опускание',passB:'противоположный проход',upB:'противоположный подъём',compress:'максимальное сжатие',pushOff:'отталкивание',flight:'фаза полёта',handPlant:'опора рукой',kneeDrive:'вынос колена',bodyShift:'перенос веса корпуса',advance:'движение вперёд',reach:'протянуть руку / ногу',grip:'контакт и хват',pull:'подтянуть тело вверх',step:'поставить ногу на следующую опору',crouch:'присесть для подготовки',takeoff:'отрыв',ascent:'подъём',apex:'верхняя точка',descent:'спуск',preLand:'перед приземлением',impact:'пик удара',recover:'восстановление',airborne:'состояние в воздухе',gravity:'гравитация берёт верх',fallFast:'ускоренное падение',touchDown:'первое касание земли',absorb:'поглотить удар',threat:'распознать угрозу',shift:'перенос веса',initiate:'начало действия',accelerate:'ускорение',peak:'пик действия',rebound:'отскок',tuck:'сгруппироваться',rollStart:'начало кувырка',inverted:'середина кувырка',rollExit:'выход из кувырка',takeFlight:'переход в полёт',bank:'крен / смена курса',cruise:'стабильный полёт',turn:'поворот',hoverUp:'лёгкий подъём',hoverDown:'лёгкое снижение',correct:'коррекция позы',strokeA:'первый гребок',catchA:'захват воды',pullA:'тяговая фаза',kickA:'удар ногами / тяга',glide:'скольжение',strokeB:'противоположный гребок',catchB:'противоположный захват',pullB:'противоположная тяга',kickB:'противоположный удар ногами',ready:'готовая стойка',anticipation:'предварительное движение',windup:'максимальная подготовка',preImpact:'перед ударом',follow:'продолжение движения',recoil:'отдача / стабилизация',rhythm:'войти в ритм',accent:'главный акцент',finish:'финальная поза',expression:'начало мимики',gesture:'жест рук / корпуса',emotionPeak:'пик эмоции',release:'начало расслабления',approach:'приблизиться к цели',objectContact:'контакт с объектом',manipulate:'взять / толкнуть / использовать / управлять',return:'вернуться в базовую позу',eyesClosed:'глаза закрыты',sleepBreath:'дыхание во сне',stir:'лёгкое движение',eyesOpen:'открыть глаза',headLift:'поднять голову / корпус',sitUp:'сесть',orient:'осмотреться',start:'начальная поза',prep:'подготовка',develop:'развитие действия',prePeak:'перед пиком',decelerate:'замедление',end:'конечная поза'}
};

const SEQUENCES = {
  idle:['neutral','inhale','rise','secondary','blink','exhale','settle','loop'],
  pose:['enterPose','settle','inhale','micro','holdPose','blink','exhale','loop'],
  walk:['contactA','downA','passA','upA','contactB','downB','passB','upB'],
  run:['contactA','compress','pushOff','flight','contactB','compress','pushOff','flight'],
  crawl:['handPlant','kneeDrive','bodyShift','advance','handPlant','kneeDrive','bodyShift','advance'],
  climb:['reach','grip','pull','step','reach','grip','pull','step'],
  jump:['neutral','crouch','compress','pushOff','takeoff','ascent','apex','descent','preLand','impact','recover','neutral'],
  fall:['airborne','gravity','descent','fallFast','fallFast','preLand','touchDown','impact','absorb','recover'],
  land:['airborne','preLand','touchDown','impact','compress','absorb','settle','recover','neutral'],
  dodge:['ready','threat','shift','initiate','accelerate','peak','rebound','return'],
  roll:['crouch','tuck','handPlant','rollStart','inverted','rollExit','recover','neutral'],
  fly:['takeFlight','ascent','bank','accelerate','cruise','turn','descent','settle'],
  hover:['takeFlight','settle','hoverUp','hoverDown','micro','correct','settle','loop'],
  swim:['strokeA','catchA','pullA','kickA','glide','strokeB','catchB','pullB','kickB','glide'],
  attack:['ready','anticipation','windup','initiate','accelerate','preImpact','impact','follow','recoil','recover','ready'],
  dance:['neutral','rhythm','accent','turn','peak','rebound','finish','release','loop'],
  gesture:['neutral','expression','gesture','emotionPeak','holdPose','release','return','loop'],
  interaction:['neutral','approach','reach','objectContact','grip','manipulate','release','return','settle'],
  rotate:['neutral','turn','turn','turn','turn','turn','turn','loop'],
  sleep:['enterPose','eyesClosed','sleepBreath','rise','exhale','micro','sleepBreath','loop'],
  wake:['eyesClosed','stir','eyesOpen','headLift','sitUp','orient','settle','neutral'],
  transition:['start','prep','shift','initiate','develop','peak','decelerate','settle','end'],
  custom:['start','prep','initiate','develop','accelerate','prePeak','peak','follow','decelerate','recover','end']
};

const ACTION_FAMILY = {
  idle:'idle',breathe:'idle',sleep:'sleep',wake:'wake',stretch:'gesture',yawn:'gesture',shiver:'idle',sitDown:'transition',standUp:'transition',lieDown:'transition',getUp:'transition',
  walk:'walk',jog:'walk',run:'run',sprint:'run',tiptoe:'walk',crawl:'crawl',climb:'climb',descend:'climb',jump:'jump',hop:'jump',leap:'jump',fall:'fall',land:'land',dodge:'dodge',roll:'roll',slide:'dodge',skid:'dodge',balanceMove:'walk',
  fly:'fly',hover:'hover',glide:'fly',dive:'fly',swoop:'fly',swim:'swim',treadWater:'hover',floatWater:'hover',surfaceWater:'swim',
  attack:'attack',punch:'attack',kick:'attack',slash:'attack',thrust:'attack',block:'attack',parry:'attack',shoot:'attack',cast:'attack',spinAttack:'attack',knockback:'dodge',
  dance:'dance',wave:'gesture',bow:'gesture',gesture:'gesture',talk:'gesture',laugh:'gesture',cry:'gesture',cheer:'gesture',applaud:'gesture',point:'gesture',nod:'gesture',shakeHead:'gesture',think:'gesture',
  eat:'interaction',drink:'interaction',pickUp:'interaction',putDown:'interaction',carry:'interaction',lift:'interaction',push:'interaction',pull:'interaction',throw:'interaction',catch:'interaction',open:'interaction',close:'interaction',useDevice:'interaction',type:'interaction',read:'interaction',write:'interaction',swingRope:'interaction',
  turn:'rotate',rotate:'rotate',lookAround:'gesture',custom:'custom'
};

const PROMPT = {
'ko-KR':{goal:'목표',subject:'대상·상황 고정',motion:'동작 설계',frame:'프레임 플랜',visual:'시각 스타일',layout:'레이아웃·등록',quality:'금지·품질 조건',final:'최종 검수',model:'모델/환경',purpose:'용도',frames:'프레임 구성',subjectType:'대상 유형',subjectDesc:'대상 설명',situation:'상황/자세',situationDetail:'상황 추가 설명',identity:'머리, 얼굴/형태, 의상, 색, 소품, 비율, 좌우 특징을 모든 프레임에서 동일하게 유지한다.',scale:'프레임마다 대상의 크기와 전체 비율을 고정한다.',action:'동작',mood:'움직임 성격',path:'이동 경로',actionDetail:'동작 추가 설명',realMotion:'정적인 그림을 단순 이동·회전한 것처럼 보이지 않게 실제 관절, 무게중심, 자세, 공간 위치가 시간에 따라 변하도록 한다.',style:'스타일',view:'시점',direction:'방향',background:'배경',environmentDetail:'환경 추가 설명',alpha:'체크무늬를 그려 투명을 흉내 내지 말고 실제 RGBA 알파 투명도를 사용한다.',order:'읽는 순서는 왼쪽→오른쪽, 위→아래다.',cells:'모든 셀은 동일한 크기와 여백을 가진다.',camera:'카메라 위치, 줌, 화각을 고정한다.',baseline:'공통 등록점과 기준선을 유지한다. 캐릭터는 접지점/몸 중심, 비행 대상은 몸 중심축, 오브젝트는 회전 중심축을 일관되게 둔다.',seamless:'마지막 프레임이 첫 프레임으로 자연스럽게 이어지는 루프를 만든다.',crop:'몸 전체, 소품, 이펙트가 셀 안에 들어오도록 충분한 여백을 둔다.',bleed:'어떤 요소도 이웃 셀 경계를 넘거나 서로 겹치지 않는다.',noText:'텍스트, 프레임 번호, 격자선, 워터마크, UI를 넣지 않는다.',noSwap:'프레임 사이에서 팔·다리 좌우, 의상, 소품, 색, 크기, 스타일이 바뀌지 않게 한다.',playback:'한 장으로 보기 좋은 것보다 실제 순서대로 재생했을 때 동작과 자세 변화가 읽히는 것을 우선한다.',extra:'추가 요구사항',finalText:'출력 전에 프레임 개수와 순서, 대상 일관성, 상황/자세, 이동 경로, 등록점, 잘림, 셀 경계 침범, 배경 조건, 루프 연결을 점검하고 문제가 있으면 수정한 뒤 결과를 제시한다.',reference:'업로드한 참조 이미지의 대상을 기준으로 사용',strip:'가로 스트립',exact:'정확히'},
'en-US':{goal:'GOAL',subject:'SUBJECT & SITUATION FIDELITY',motion:'MOTION DESIGN',frame:'FRAME PLAN',visual:'VISUAL STYLE',layout:'LAYOUT & REGISTRATION',quality:'NEGATIVE & QUALITY CONSTRAINTS',final:'FINAL CHECK',model:'Model / environment',purpose:'Intended use',frames:'Frame structure',subjectType:'Subject type',subjectDesc:'Subject description',situation:'Situation / pose',situationDetail:'Situation details',identity:'Preserve hairstyle/shape, face or defining geometry, outfit, colors, props, proportions, and left/right-specific features across every frame.',scale:'Keep subject scale and overall proportions consistent in every frame.',action:'Action',mood:'Motion character',path:'Motion path',actionDetail:'Action details',realMotion:'Animate real changes in joints, balance, pose and spatial position over time. Do not fake motion by only translating or rotating a static drawing.',style:'Style',view:'View',direction:'Direction',background:'Background',environmentDetail:'Environment details',alpha:'Use genuine RGBA alpha transparency. Do not draw a checkerboard to imitate transparency.',order:'Read frames left to right, then top to bottom.',cells:'Every cell must have identical dimensions and consistent padding.',camera:'Lock camera position, zoom and viewing angle across all frames.',baseline:'Keep a common registration point and baseline. Use foot/body center for grounded characters, body center axis for airborne subjects, and a consistent rotation center for objects.',seamless:'Make the final frame transition naturally back into the first frame for a seamless loop.',crop:'Keep the full body/object, props and effects safely inside each cell with generous margins.',bleed:'Nothing may cross into a neighboring cell or overlap another frame.',noText:'No text, frame numbers, grid lines, watermarks or UI overlays.',noSwap:'Do not swap left/right limbs, costume parts, props, colors, scale or style between frames.',playback:'Prioritize a sequence whose action and pose changes read correctly in playback, not merely a sheet that looks attractive as one image.',extra:'Additional requirement',finalText:'Before presenting the result, verify frame count and order, subject consistency, situation/pose, motion path, registration, cropping, cell bleed, background requirements and loop continuity. Correct visible issues first.',reference:'Use the uploaded reference image as the subject identity reference',strip:'horizontal strip',exact:'exactly'},
'ja-JP':{goal:'目標',subject:'対象・状況の一貫性',motion:'動作設計',frame:'フレームプラン',visual:'ビジュアルスタイル',layout:'レイアウト・登録',quality:'禁止・品質条件',final:'最終確認',model:'モデル / 環境',purpose:'用途',frames:'フレーム構成',subjectType:'対象タイプ',subjectDesc:'対象の説明',situation:'状況 / ポーズ',situationDetail:'状況の追加説明',identity:'髪型/形状、顔や特徴的形状、衣装、色、小物、比率、左右固有の特徴を全フレームで同一に保つ。',scale:'対象のサイズと全体比率を全フレームで一定にする。',action:'動作',mood:'動きの性格',path:'移動経路',actionDetail:'動作の追加説明',realMotion:'静止画を単に平行移動・回転したようにせず、関節、重心、姿勢、空間位置が時間とともに実際に変化するようにする。',style:'スタイル',view:'視点',direction:'方向',background:'背景',environmentDetail:'環境の追加説明',alpha:'市松模様で透明を偽装せず、実際のRGBAアルファ透明を使う。',order:'左→右、上→下の順に読む。',cells:'すべてのセルは同じサイズと余白にする。',camera:'カメラ位置、ズーム、画角を全フレームで固定する。',baseline:'共通の登録点と基準を保つ。地上キャラクターは足元/体中心、空中対象は体の中心軸、物体は回転中心を一貫させる。',seamless:'最終フレームから最初のフレームへ自然につながるループにする。',crop:'身体/物体、小物、効果がセル内に安全に収まる余白を確保する。',bleed:'隣のセルへはみ出したり他フレームと重なったりしない。',noText:'文字、フレーム番号、格子線、透かし、UIを入れない。',noSwap:'フレーム間で左右の手足、衣装、小物、色、サイズ、スタイルを変えない。',playback:'1枚の見栄えより、順番に再生したとき動作と姿勢変化が正しく読めることを優先する。',extra:'追加要件',finalText:'出力前にフレーム数と順序、対象の一貫性、状況/ポーズ、移動経路、登録点、切れ、セル越境、背景条件、ループ連続性を確認し、問題があれば修正してから提示する。',reference:'アップロードした参照画像を対象の同一性基準として使う',strip:'横ストリップ',exact:'正確に'},
'zh-CN':{goal:'目标',subject:'主体与情境一致性',motion:'动作设计',frame:'帧计划',visual:'视觉风格',layout:'布局与注册',quality:'禁止与质量条件',final:'最终检查',model:'模型 / 环境',purpose:'用途',frames:'帧结构',subjectType:'主体类型',subjectDesc:'主体描述',situation:'情境 / 姿势',situationDetail:'情境补充说明',identity:'在所有帧中保持发型/形状、面部或关键几何特征、服装、颜色、道具、比例以及左右特征一致。',scale:'所有帧中的主体大小与整体比例保持一致。',action:'动作',mood:'动作风格',path:'移动路径',actionDetail:'动作补充说明',realMotion:'让关节、重心、姿势和空间位置随时间真实变化，不要只通过平移或旋转静态图来假装运动。',style:'风格',view:'视角',direction:'方向',background:'背景',environmentDetail:'环境补充说明',alpha:'使用真实RGBA Alpha透明度，不要绘制棋盘格来模拟透明。',order:'阅读顺序为从左到右、从上到下。',cells:'所有单元格尺寸与内边距必须一致。',camera:'所有帧锁定相机位置、缩放和视角。',baseline:'保持统一注册点和基准。地面角色使用脚部/身体中心，空中主体使用身体中心轴，物体使用统一旋转中心。',seamless:'让最后一帧自然过渡回第一帧，形成无缝循环。',crop:'让完整身体/物体、道具与特效安全位于单元格内并留足边距。',bleed:'任何元素都不能进入相邻单元格或与其他帧重叠。',noText:'不要文字、帧编号、网格线、水印或UI覆盖。',noSwap:'帧之间不要交换左右肢体、服装部件、道具、颜色、大小或风格。',playback:'优先保证按顺序播放时动作和姿势变化清晰，而不是只追求整张图好看。',extra:'附加要求',finalText:'输出前检查帧数与顺序、主体一致性、情境/姿势、移动路径、注册、裁切、跨格、背景条件与循环连续性。先修正可见问题再给出结果。',reference:'使用上传的参考图作为主体身份基准',strip:'横向条带',exact:'准确'},
'es-ES':{goal:'OBJETIVO',subject:'FIDELIDAD DEL SUJETO Y LA SITUACIÓN',motion:'DISEÑO DEL MOVIMIENTO',frame:'PLAN DE FOTOGRAMAS',visual:'ESTILO VISUAL',layout:'DISEÑO Y REGISTRO',quality:'RESTRICCIONES NEGATIVAS Y DE CALIDAD',final:'COMPROBACIÓN FINAL',model:'Modelo / entorno',purpose:'Uso previsto',frames:'Estructura de fotogramas',subjectType:'Tipo de sujeto',subjectDesc:'Descripción del sujeto',situation:'Situación / pose',situationDetail:'Detalles de la situación',identity:'Conserva peinado/forma, rostro o geometría distintiva, ropa, colores, accesorios, proporciones y rasgos específicos de izquierda/derecha en todos los fotogramas.',scale:'Mantén la escala y proporciones generales del sujeto en todos los fotogramas.',action:'Acción',mood:'Carácter del movimiento',path:'Trayectoria',actionDetail:'Detalles de la acción',realMotion:'Anima cambios reales de articulaciones, equilibrio, pose y posición espacial con el tiempo. No simules movimiento limitándote a trasladar o rotar un dibujo estático.',style:'Estilo',view:'Vista',direction:'Dirección',background:'Fondo',environmentDetail:'Detalles del entorno',alpha:'Usa transparencia RGBA real. No dibujes un patrón de tablero para imitar transparencia.',order:'Lee los fotogramas de izquierda a derecha y de arriba abajo.',cells:'Todas las celdas deben tener dimensiones y márgenes consistentes.',camera:'Bloquea posición de cámara, zoom y ángulo en todos los fotogramas.',baseline:'Mantén un punto de registro y referencia común. En personajes terrestres usa pies/centro corporal, en sujetos aéreos el eje central del cuerpo y en objetos un centro de rotación consistente.',seamless:'Haz que el último fotograma conecte de forma natural con el primero para un bucle continuo.',crop:'Mantén cuerpo/objeto completo, accesorios y efectos dentro de cada celda con margen suficiente.',bleed:'Nada puede invadir una celda vecina ni solaparse con otro fotograma.',noText:'Sin texto, números de fotograma, líneas de cuadrícula, marcas de agua ni UI.',noSwap:'No intercambies extremidades izquierda/derecha, ropa, accesorios, colores, escala ni estilo entre fotogramas.',playback:'Prioriza que la acción y los cambios de pose se lean correctamente en reproducción, no solo que la hoja sea atractiva como imagen única.',extra:'Requisito adicional',finalText:'Antes de mostrar el resultado, verifica cantidad y orden de fotogramas, consistencia del sujeto, situación/pose, trayectoria, registro, recorte, invasión de celdas, fondo y continuidad del bucle. Corrige primero los problemas visibles.',reference:'Usa la imagen de referencia subida como identidad del sujeto',strip:'tira horizontal',exact:'exactamente'},
'fr-FR':{goal:'OBJECTIF',subject:'FIDÉLITÉ DU SUJET ET DE LA SITUATION',motion:'CONCEPTION DU MOUVEMENT',frame:'PLAN DES IMAGES',visual:'STYLE VISUEL',layout:'MISE EN PAGE ET REPÉRAGE',quality:'CONTRAINTES NÉGATIVES ET DE QUALITÉ',final:'VÉRIFICATION FINALE',model:'Modèle / environnement',purpose:'Usage prévu',frames:'Structure des images',subjectType:'Type de sujet',subjectDesc:'Description du sujet',situation:'Situation / pose',situationDetail:'Détails de la situation',identity:'Préserver coiffure/forme, visage ou géométrie distinctive, tenue, couleurs, accessoires, proportions et caractéristiques gauche/droite sur toutes les images.',scale:'Conserver la même échelle et les mêmes proportions globales du sujet dans toutes les images.',action:'Action',mood:'Caractère du mouvement',path:'Trajectoire',actionDetail:'Détails de l’action',realMotion:'Animer de vrais changements d’articulations, d’équilibre, de pose et de position dans l’espace au fil du temps. Ne pas simuler le mouvement en déplaçant ou faisant simplement tourner un dessin statique.',style:'Style',view:'Vue',direction:'Direction',background:'Fond',environmentDetail:'Détails de l’environnement',alpha:'Utiliser une vraie transparence alpha RGBA. Ne pas dessiner de damier pour imiter la transparence.',order:'Lire les images de gauche à droite puis de haut en bas.',cells:'Toutes les cellules doivent avoir les mêmes dimensions et des marges cohérentes.',camera:'Verrouiller position de caméra, zoom et angle de vue sur toutes les images.',baseline:'Conserver un point de repère commun. Pour un personnage au sol utiliser pieds/centre du corps, pour un sujet aérien l’axe central du corps et pour un objet un centre de rotation constant.',seamless:'Faire revenir naturellement la dernière image vers la première pour une boucle fluide.',crop:'Garder corps/objet complet, accessoires et effets à l’intérieur de chaque cellule avec une marge suffisante.',bleed:'Aucun élément ne doit déborder dans une cellule voisine ni chevaucher une autre image.',noText:'Aucun texte, numéro d’image, ligne de grille, filigrane ni interface.',noSwap:'Ne pas inverser membres gauche/droite, vêtements, accessoires, couleurs, échelle ou style entre les images.',playback:'Privilégier une séquence dont l’action et les changements de pose sont lisibles en lecture, plutôt qu’une planche seulement jolie comme image fixe.',extra:'Exigence supplémentaire',finalText:'Avant de présenter le résultat, vérifier nombre et ordre des images, cohérence du sujet, situation/pose, trajectoire, repérage, recadrage, débordement, fond et continuité de boucle. Corriger d’abord les défauts visibles.',reference:'Utiliser l’image de référence téléversée comme identité du sujet',strip:'bande horizontale',exact:'exactement'},
'de-DE':{goal:'ZIEL',subject:'MOTIV- & SITUATIONSKONSISTENZ',motion:'BEWEGUNGSDESIGN',frame:'FRAME-PLAN',visual:'VISUELLER STIL',layout:'LAYOUT & REGISTRIERUNG',quality:'NEGATIVE & QUALITÄTSBEDINGUNGEN',final:'ABSCHLUSSPRÜFUNG',model:'Modell / Umgebung',purpose:'Verwendungszweck',frames:'Frame-Struktur',subjectType:'Motivtyp',subjectDesc:'Motivbeschreibung',situation:'Situation / Pose',situationDetail:'Situationsdetails',identity:'Frisur/Form, Gesicht oder prägende Geometrie, Kleidung, Farben, Requisiten, Proportionen und links/rechts-spezifische Merkmale in allen Frames beibehalten.',scale:'Skalierung und Gesamtproportionen des Motivs in allen Frames konstant halten.',action:'Aktion',mood:'Bewegungscharakter',path:'Bewegungspfad',actionDetail:'Aktionsdetails',realMotion:'Echte Änderungen von Gelenken, Balance, Pose und räumlicher Position über die Zeit animieren. Bewegung nicht nur durch Verschieben oder Drehen einer statischen Zeichnung vortäuschen.',style:'Stil',view:'Ansicht',direction:'Richtung',background:'Hintergrund',environmentDetail:'Umgebungsdetails',alpha:'Echte RGBA-Alpha-Transparenz verwenden. Kein Schachbrettmuster als Transparenzsimulation zeichnen.',order:'Frames von links nach rechts und dann von oben nach unten lesen.',cells:'Alle Zellen müssen identische Abmessungen und konsistente Innenabstände haben.',camera:'Kameraposition, Zoom und Blickwinkel über alle Frames fixieren.',baseline:'Einen gemeinsamen Registrierungspunkt beibehalten. Bei Figuren am Boden Füße/Körperzentrum, bei fliegenden Motiven die Körpermittelachse und bei Objekten ein konstantes Rotationszentrum verwenden.',seamless:'Den letzten Frame natürlich in den ersten überführen, damit eine nahtlose Schleife entsteht.',crop:'Körper/Objekt, Requisiten und Effekte vollständig mit genügend Rand in jeder Zelle halten.',bleed:'Nichts darf in Nachbarzellen ragen oder andere Frames überlappen.',noText:'Kein Text, keine Frame-Nummern, Rasterlinien, Wasserzeichen oder UI-Overlays.',noSwap:'Links/rechts-Gliedmaßen, Kostümteile, Requisiten, Farben, Skalierung oder Stil zwischen Frames nicht vertauschen.',playback:'Eine Sequenz priorisieren, deren Aktion und Posenwechsel in der Wiedergabe klar lesbar sind, nicht nur ein attraktives Einzelbild.',extra:'Zusätzliche Anforderung',finalText:'Vor der Ausgabe Frame-Anzahl und Reihenfolge, Motivkonsistenz, Situation/Pose, Bewegungspfad, Registrierung, Beschnitt, Zellüberlauf, Hintergrundbedingungen und Schleifenübergang prüfen. Sichtbare Probleme zuerst korrigieren.',reference:'Das hochgeladene Referenzbild als Identitätsreferenz des Motivs verwenden',strip:'horizontaler Streifen',exact:'genau'},
'pt-BR':{goal:'OBJETIVO',subject:'FIDELIDADE DO SUJEITO E DA SITUAÇÃO',motion:'DESIGN DO MOVIMENTO',frame:'PLANO DE QUADROS',visual:'ESTILO VISUAL',layout:'LAYOUT E REGISTRO',quality:'RESTRIÇÕES NEGATIVAS E DE QUALIDADE',final:'VERIFICAÇÃO FINAL',model:'Modelo / ambiente',purpose:'Uso pretendido',frames:'Estrutura dos quadros',subjectType:'Tipo de sujeito',subjectDesc:'Descrição do sujeito',situation:'Situação / pose',situationDetail:'Detalhes da situação',identity:'Preserve cabelo/forma, rosto ou geometria marcante, roupa, cores, adereços, proporções e características específicas de esquerda/direita em todos os quadros.',scale:'Mantenha escala e proporções gerais do sujeito consistentes em todos os quadros.',action:'Ação',mood:'Caráter do movimento',path:'Trajetória',actionDetail:'Detalhes da ação',realMotion:'Anime mudanças reais em articulações, equilíbrio, pose e posição espacial ao longo do tempo. Não simule movimento apenas transladando ou girando um desenho estático.',style:'Estilo',view:'Visão',direction:'Direção',background:'Fundo',environmentDetail:'Detalhes do ambiente',alpha:'Use transparência alfa RGBA real. Não desenhe padrão quadriculado para imitar transparência.',order:'Leia os quadros da esquerda para a direita e de cima para baixo.',cells:'Todas as células devem ter dimensões idênticas e espaçamento consistente.',camera:'Trave posição da câmera, zoom e ângulo de visão em todos os quadros.',baseline:'Mantenha um ponto de registro comum. Para personagens no chão use pés/centro do corpo; para sujeitos aéreos, o eixo central do corpo; para objetos, um centro de rotação consistente.',seamless:'Faça o último quadro transicionar naturalmente de volta ao primeiro para criar um loop contínuo.',crop:'Mantenha corpo/objeto inteiro, adereços e efeitos dentro de cada célula com margem suficiente.',bleed:'Nada pode invadir uma célula vizinha nem sobrepor outro quadro.',noText:'Sem texto, números de quadro, linhas de grade, marcas d’água ou UI.',noSwap:'Não troque membros esquerda/direita, partes da roupa, adereços, cores, escala ou estilo entre quadros.',playback:'Priorize uma sequência em que a ação e as mudanças de pose sejam legíveis na reprodução, não apenas uma folha bonita como imagem única.',extra:'Requisito adicional',finalText:'Antes de apresentar o resultado, verifique quantidade e ordem dos quadros, consistência do sujeito, situação/pose, trajetória, registro, corte, invasão de células, fundo e continuidade do loop. Corrija primeiro os problemas visíveis.',reference:'Use a imagem de referência enviada como identidade do sujeito',strip:'faixa horizontal',exact:'exatamente'},
'it-IT':{goal:'OBIETTIVO',subject:'COERENZA DEL SOGGETTO E DELLA SITUAZIONE',motion:'PROGETTAZIONE DEL MOVIMENTO',frame:'PIANO DEI FOTOGRAMMI',visual:'STILE VISIVO',layout:'LAYOUT E REGISTRAZIONE',quality:'VINCOLI NEGATIVI E DI QUALITÀ',final:'CONTROLLO FINALE',model:'Modello / ambiente',purpose:'Uso previsto',frames:'Struttura dei fotogrammi',subjectType:'Tipo di soggetto',subjectDesc:'Descrizione del soggetto',situation:'Situazione / posa',situationDetail:'Dettagli della situazione',identity:'Mantieni acconciatura/forma, volto o geometria distintiva, abbigliamento, colori, accessori, proporzioni e caratteristiche specifiche destra/sinistra in tutti i fotogrammi.',scale:'Mantieni scala e proporzioni generali del soggetto coerenti in tutti i fotogrammi.',action:'Azione',mood:'Carattere del movimento',path:'Percorso',actionDetail:'Dettagli dell’azione',realMotion:'Anima veri cambiamenti di articolazioni, equilibrio, posa e posizione nello spazio nel tempo. Non simulare il movimento limitandoti a spostare o ruotare un disegno statico.',style:'Stile',view:'Vista',direction:'Direzione',background:'Sfondo',environmentDetail:'Dettagli dell’ambiente',alpha:'Usa vera trasparenza alpha RGBA. Non disegnare una scacchiera per imitare la trasparenza.',order:'Leggi i fotogrammi da sinistra a destra e dall’alto in basso.',cells:'Tutte le celle devono avere dimensioni identiche e spaziatura coerente.',camera:'Blocca posizione camera, zoom e angolo di vista in tutti i fotogrammi.',baseline:'Mantieni un punto di registrazione comune. Per personaggi a terra usa piedi/centro del corpo, per soggetti aerei l’asse centrale del corpo, per oggetti un centro di rotazione coerente.',seamless:'Fai passare naturalmente l’ultimo fotogramma al primo per un loop continuo.',crop:'Mantieni corpo/oggetto intero, accessori ed effetti all’interno di ogni cella con margine sufficiente.',bleed:'Nessun elemento deve invadere celle vicine o sovrapporsi ad altri fotogrammi.',noText:'Niente testo, numeri di fotogramma, linee di griglia, watermark o UI.',noSwap:'Non invertire arti destra/sinistra, parti del costume, accessori, colori, scala o stile tra fotogrammi.',playback:'Dai priorità a una sequenza in cui azione e cambi di posa siano leggibili in riproduzione, non solo a una tavola bella come immagine singola.',extra:'Requisito aggiuntivo',finalText:'Prima di mostrare il risultato, verifica numero e ordine dei fotogrammi, coerenza del soggetto, situazione/posa, percorso, registrazione, ritaglio, sconfinamento tra celle, sfondo e continuità del loop. Correggi prima i problemi visibili.',reference:'Usa l’immagine di riferimento caricata come identità del soggetto',strip:'striscia orizzontale',exact:'esattamente'},
'ru-RU':{goal:'ЦЕЛЬ',subject:'СОГЛАСОВАННОСТЬ ОБЪЕКТА И СИТУАЦИИ',motion:'ДИЗАЙН ДВИЖЕНИЯ',frame:'ПЛАН КАДРОВ',visual:'ВИЗУАЛЬНЫЙ СТИЛЬ',layout:'КОМПОНОВКА И РЕГИСТРАЦИЯ',quality:'НЕГАТИВНЫЕ И КАЧЕСТВЕННЫЕ ОГРАНИЧЕНИЯ',final:'ФИНАЛЬНАЯ ПРОВЕРКА',model:'Модель / среда',purpose:'Назначение',frames:'Структура кадров',subjectType:'Тип объекта',subjectDesc:'Описание объекта',situation:'Ситуация / поза',situationDetail:'Детали ситуации',identity:'Сохранять причёску/форму, лицо или характерную геометрию, одежду, цвета, предметы, пропорции и лево/право-специфические признаки во всех кадрах.',scale:'Сохранять одинаковый масштаб и общие пропорции объекта во всех кадрах.',action:'Действие',mood:'Характер движения',path:'Траектория',actionDetail:'Детали действия',realMotion:'Анимировать реальные изменения суставов, баланса, позы и положения в пространстве со временем. Не имитировать движение простым переносом или вращением статичного рисунка.',style:'Стиль',view:'Ракурс',direction:'Направление',background:'Фон',environmentDetail:'Детали среды',alpha:'Использовать настоящую RGBA alpha-прозрачность. Не рисовать шахматный узор для имитации прозрачности.',order:'Читать кадры слева направо, затем сверху вниз.',cells:'Все ячейки должны иметь одинаковые размеры и отступы.',camera:'Фиксировать положение камеры, зум и угол обзора во всех кадрах.',baseline:'Сохранять общий регистрационный ориентир. Для наземного персонажа использовать стопы/центр тела, для воздушного объекта — центральную ось тела, для предметов — постоянный центр вращения.',seamless:'Сделать естественный переход последнего кадра к первому для бесшовного цикла.',crop:'Полностью помещать тело/объект, предметы и эффекты внутри каждой ячейки с достаточным запасом.',bleed:'Ничто не должно выходить в соседнюю ячейку или перекрываться с другим кадром.',noText:'Без текста, номеров кадров, линий сетки, водяных знаков и UI.',noSwap:'Не менять местами левые/правые конечности, части костюма, предметы, цвета, масштаб или стиль между кадрами.',playback:'Приоритет — последовательность, в которой действие и изменение поз читаются при воспроизведении, а не просто красиво выглядят на одном листе.',extra:'Дополнительное требование',finalText:'Перед выводом проверить количество и порядок кадров, согласованность объекта, ситуацию/позу, траекторию, регистрацию, обрезку, выход за ячейки, требования к фону и непрерывность цикла. Сначала исправить видимые проблемы.',reference:'Использовать загруженное референсное изображение как основу идентичности объекта',strip:'горизонтальная полоса',exact:'ровно'}
};


const PROMPT_EXTRA = {
  'id-ID':{goal:'TUJUAN',subject:'KONSISTENSI SUBJEK & SITUASI',motion:'DESAIN GERAK',frame:'RENCANA FRAME',visual:'GAYA VISUAL',layout:'TATA LETAK & REGISTRASI',quality:'BATASAN NEGATIF & KUALITAS',final:'PEMERIKSAAN AKHIR',model:'Model / lingkungan',purpose:'Tujuan penggunaan',frames:'Struktur frame',subjectType:'Jenis subjek',subjectDesc:'Deskripsi subjek',situation:'Situasi / pose',situationDetail:'Detail situasi',identity:'Pertahankan rambut/bentuk, wajah atau geometri khas, pakaian, warna, properti, proporsi, serta ciri kiri/kanan secara konsisten di semua frame.',scale:'Pertahankan skala dan proporsi keseluruhan subjek di semua frame.',action:'Aksi',mood:'Karakter gerak',path:'Jalur gerak',actionDetail:'Detail aksi',realMotion:'Animasikan perubahan nyata pada sendi, keseimbangan, pose, dan posisi ruang sepanjang waktu. Jangan mensimulasikan gerak hanya dengan menggeser atau memutar gambar statis.',style:'Gaya',view:'Sudut pandang',direction:'Arah',background:'Latar',environmentDetail:'Detail lingkungan',alpha:'Gunakan transparansi alpha RGBA yang nyata. Jangan menggambar pola papan catur untuk meniru transparansi.',order:'Baca frame dari kiri ke kanan, lalu dari atas ke bawah.',cells:'Semua sel harus berukuran sama dengan jarak yang konsisten.',camera:'Kunci posisi kamera, zoom, dan sudut pandang di semua frame.',baseline:'Pertahankan titik registrasi bersama. Untuk karakter di tanah gunakan kaki/pusat tubuh; untuk subjek di udara gunakan sumbu pusat tubuh; untuk objek gunakan pusat rotasi yang konsisten.',seamless:'Buat frame terakhir kembali ke frame pertama secara alami untuk loop yang mulus.',crop:'Pastikan seluruh tubuh/objek, properti, dan efek berada di dalam setiap sel dengan margin yang cukup.',bleed:'Tidak ada elemen yang boleh masuk ke sel tetangga atau menimpa frame lain.',noText:'Tanpa teks, nomor frame, garis grid, watermark, atau UI.',noSwap:'Jangan menukar anggota tubuh kiri/kanan, bagian pakaian, properti, warna, skala, atau gaya antarframe.',playback:'Prioritaskan urutan yang gerak dan perubahan posenya terbaca saat diputar, bukan hanya lembar yang terlihat bagus sebagai satu gambar.',extra:'Persyaratan tambahan',finalText:'Sebelum menampilkan hasil, periksa jumlah dan urutan frame, konsistensi subjek, situasi/pose, jalur gerak, registrasi, pemotongan, kebocoran antar sel, latar, dan kesinambungan loop. Perbaiki masalah yang terlihat terlebih dahulu.',reference:'Gunakan gambar referensi yang diunggah sebagai identitas subjek',strip:'strip horizontal',exact:'tepat'},
  'tr-TR':{goal:'AMAÇ',subject:'KONU VE DURUM TUTARLILIĞI',motion:'HAREKET TASARIMI',frame:'KARE PLANI',visual:'GÖRSEL STİL',layout:'DÜZEN VE KAYIT',quality:'NEGATİF VE KALİTE KISITLARI',final:'SON KONTROL',model:'Model / ortam',purpose:'Kullanım amacı',frames:'Kare yapısı',subjectType:'Konu türü',subjectDesc:'Konu açıklaması',situation:'Durum / poz',situationDetail:'Durum ayrıntısı',identity:'Saç/biçim, yüz veya ayırt edici geometri, kıyafet, renkler, aksesuarlar, oranlar ve sağ/sol özelliklerini tüm karelerde aynı tut.',scale:'Konunun ölçeğini ve genel oranlarını tüm karelerde tutarlı tut.',action:'Hareket',mood:'Hareket karakteri',path:'Hareket yolu',actionDetail:'Hareket ayrıntısı',realMotion:'Zaman içinde eklemlerde, dengede, pozda ve mekânsal konumda gerçek değişiklikler üret. Statik bir çizimi yalnızca kaydırıp döndürerek hareket taklidi yapma.',style:'Stil',view:'Görünüm',direction:'Yön',background:'Arka plan',environmentDetail:'Ortam ayrıntısı',alpha:'Gerçek RGBA alpha şeffaflığı kullan. Şeffaflığı taklit etmek için dama deseni çizme.',order:'Kareleri soldan sağa, sonra yukarıdan aşağıya oku.',cells:'Tüm hücreler aynı boyutta ve tutarlı aralıklı olmalı.',camera:'Kamera konumunu, zoomu ve görüş açısını tüm karelerde sabitle.',baseline:'Ortak bir kayıt noktası koru. Yerdeki karakterlerde ayakları/gövde merkezini, havadaki konularda gövde merkez eksenini, nesnelerde tutarlı dönüş merkezini kullan.',seamless:'Kesintisiz döngü için son kareyi ilk kareye doğal biçimde bağla.',crop:'Tüm gövde/nesne, aksesuarlar ve efektler her hücre içinde yeterli boşlukla tam görünsün.',bleed:'Hiçbir öğe komşu hücreye taşmasın veya başka kareyle çakışmasın.',noText:'Metin, kare numarası, ızgara çizgisi, filigran veya UI ekleme.',noSwap:'Kareler arasında sağ/sol uzuvları, kıyafet parçalarını, aksesuarları, renkleri, ölçeği veya stili değiştirme.',playback:'Tek bir güzel sayfadan çok, oynatıldığında hareket ve poz değişimlerinin okunaklı olduğu bir diziye öncelik ver.',extra:'Ek gereksinim',finalText:'Sonucu göstermeden önce kare sayısı ve sırasını, konu tutarlılığını, durum/pozu, hareket yolunu, kayıt noktasını, kırpmayı, hücre taşmasını, arka planı ve döngü sürekliliğini kontrol et. Görünür sorunları önce düzelt.',reference:'Yüklenen referans görselini konu kimliği olarak kullan',strip:'yatay şerit',exact:'tam olarak'}
};

const GENERIC_PHASES = {
  'id-ID':['pose awal','persiapan','gerak dimulai','perubahan bobot / arah','percepatan','puncak gerak','lanjutan','pemulihan','kembali stabil','siap terhubung ke frame awal'],
  'tr-TR':['başlangıç pozu','hazırlık','hareketin başlangıcı','ağırlık / yön değişimi','hızlanma','hareketin zirvesi','devam hareketi','toparlanma','yeniden dengelenme','ilk kareye bağlanmaya hazır']
};

const MIXED_INPUT_NOTE = {
  'ko-KR':'자유 입력 설명이 다른 언어로 작성되어 있어도 의미를 그대로 해석하고, 나머지 지시는 이 프롬프트의 언어를 따른다.',
  'en-US':'If free-text descriptions are written in another language, interpret their meaning faithfully while keeping the rest of the instructions in this prompt language.',
  'ja-JP':'自由入力の説明が別の言語でも意味を忠実に解釈し、それ以外の指示はこのプロンプトの言語に従う。',
  'zh-CN':'即使自由输入的描述使用其他语言，也要忠实理解其含义，其余指令保持为当前提示词语言。',
  'es-ES':'Si las descripciones de texto libre están en otro idioma, interpreta fielmente su significado y mantén el resto de las instrucciones en el idioma de este prompt.',
  'fr-FR':'Si les descriptions libres sont dans une autre langue, interprétez fidèlement leur sens tout en gardant le reste des instructions dans la langue de ce prompt.',
  'de-DE':'Wenn Freitext-Beschreibungen in einer anderen Sprache vorliegen, interpretiere ihre Bedeutung getreu und halte die übrigen Anweisungen in der Sprache dieses Prompts.',
  'pt-BR':'Se as descrições livres estiverem em outro idioma, interprete fielmente o significado e mantenha o restante das instruções no idioma deste prompt.',
  'it-IT':'Se le descrizioni libere sono in un’altra lingua, interpretane fedelmente il significato mantenendo il resto delle istruzioni nella lingua di questo prompt.',
  'ru-RU':'Если свободные описания написаны на другом языке, точно интерпретируйте их смысл, сохраняя остальные инструкции на языке этого промпта.',
  'id-ID':'Jika deskripsi teks bebas ditulis dalam bahasa lain, tafsirkan maknanya secara setia dan pertahankan instruksi lainnya dalam bahasa prompt ini.',
  'tr-TR':'Serbest metin açıklamaları başka bir dildeyse anlamını doğru yorumla ve diğer talimatları bu promptun dilinde tut.'
};

function getFamily(action, situation){
  if((action==='idle' || action==='breathe') && situation && !['neutral','standing'].includes(situation)) return 'pose';
  return ACTION_FAMILY[action] || 'custom';
}

function resample(base, count){
  if(count<=1) return [base[0]];
  if(count===base.length) return [...base];
  const out=[];
  for(let i=0;i<count;i++) out.push(base[Math.round(i*(base.length-1)/(count-1))]);
  return out;
}

export function getFramePlan(action, count, lang='ko-KR', detail='', situation='neutral'){
  const l=normalizeLanguage(lang);
  const family=getFamily(action,situation);
  const keys=SEQUENCES[family] || SEQUENCES.custom;
  const dict=PHASES[l];
  let base;
  if(dict){
    base=keys.map(k=>dict[k] || PHASES['en-US'][k] || k);
  }else{
    const generic=GENERIC_PHASES[l] || GENERIC_PHASES['id-ID'];
    base=generic.map((phase,i)=>`${phase} · ${tOption(l,'action',action)}`);
  }
  if(family==='rotate'){
    const degrees=['0°','45°','90°','135°','180°','225°','270°','315°'];
    base=degrees.map((d,i)=>`${d} · ${i===0?tOption(l,'direction','camera'):i===4?tOption(l,'direction','away'):tOption(l,'action','rotate')}`);
  }
  const out=resample(base, Number(count));
  if(detail && out.length) out[Math.floor(out.length/2)] += ` — ${detail}`;
  return out;
}

export function getPresetTitle(id, lang='en-US'){
  return tOption(normalizeLanguage(lang),'preset',id);
}

function bullet(label, value){ return `- ${label}: ${value}`; }

export function buildPrompt(state){
  const lang=normalizeLanguage(state.promptLanguage || 'en-US');
  const p=PROMPT[lang] || PROMPT_EXTRA[lang] || PROMPT['en-US'];
  const frameCount=Number(state.frameCount) || 16;
  const framePlan=getFramePlan(state.action, frameCount, lang, (state.actionDetail||'').trim(), state.situation);
  const subjectDesc=(state.subject||'').trim() || p.reference;
  const situationDetail=(state.situationDetail||'').trim();
  const envExtra=(state.environmentDetail||'').trim();
  const actionExtra=(state.actionDetail||'').trim();
  const extra=(state.extra||'').trim();
  const title=getPresetTitle(state.preset || 'custom', lang);
  const grid=state.gridLayout==='strip' ? p.strip : state.gridLayout;
  const frameText=framePlan.map((x,i)=>`${String(i+1).padStart(2,'0')}. ${x}`).join('\n');
  const lines=[];
  lines.push(p.goal);
  lines.push(bullet(p.model,state.modelTarget));
  lines.push(bullet(p.purpose,title));
  lines.push(bullet(p.frames,`${p.exact} ${frameCount} · ${grid}`));
  lines.push('');
  lines.push(p.subject);
  lines.push(bullet(p.subjectType,tOption(lang,'subjectType',state.subjectType)));
  lines.push(bullet(p.subjectDesc,subjectDesc));
  lines.push(bullet(p.situation,tOption(lang,'situation',state.situation || 'neutral')));
  if(situationDetail) lines.push(bullet(p.situationDetail,situationDetail));
  if(state.uiLanguage && normalizeLanguage(state.uiLanguage)!==lang) lines.push(`- ${MIXED_INPUT_NOTE[lang] || MIXED_INPUT_NOTE['en-US']}`);
  if(state.lockIdentity) lines.push(`- ${p.identity}`);
  if(state.lockScale) lines.push(`- ${p.scale}`);
  lines.push('');
  lines.push(p.motion);
  lines.push(bullet(p.action,tOption(lang,'action',state.action)));
  lines.push(bullet(p.mood,tOption(lang,'mood',state.motionMood)));
  lines.push(bullet(p.path,tOption(lang,'motionPath',state.motionPath || 'stationary')));
  if(actionExtra) lines.push(bullet(p.actionDetail,actionExtra));
  lines.push(`- ${p.realMotion}`);
  lines.push('');
  lines.push(p.frame);
  lines.push(frameText);
  lines.push('');
  lines.push(p.visual);
  lines.push(bullet(p.style,tOption(lang,'style',state.style)));
  lines.push(bullet(p.view,tOption(lang,'view',state.view)));
  lines.push(bullet(p.direction,tOption(lang,'direction',state.direction)));
  lines.push(bullet(p.background,tOption(lang,'background',state.background)));
  if(envExtra) lines.push(bullet(p.environmentDetail,envExtra));
  if(state.background==='transparent' && state.trueAlpha) lines.push(`- ${p.alpha}`);
  lines.push('');
  lines.push(p.layout);
  lines.push(`- ${p.order}`);
  lines.push(`- ${p.cells}`);
  if(state.lockCamera) lines.push(`- ${p.camera}`);
  if(state.lockBaseline) lines.push(`- ${p.baseline}`);
  if(state.seamlessLoop) lines.push(`- ${p.seamless}`);
  if(state.noCrop) lines.push(`- ${p.crop}`);
  if(state.noBleed) lines.push(`- ${p.bleed}`);
  lines.push('');
  lines.push(p.quality);
  if(state.noText) lines.push(`- ${p.noText}`);
  lines.push(`- ${p.noSwap}`);
  lines.push(`- ${p.playback}`);
  if(extra) lines.push(bullet(p.extra,extra));
  lines.push('');
  lines.push(p.final);
  lines.push(p.finalText);
  return lines.join('\n');
}
